config/routes.rb
Estedad::Application.routes.draw do

  root to: 'blogs#index'
  
  resources :pages
  resources :blogs
  resources :forms do
    resources :filled_forms, only: [:show, :create, :update, :new, :edit]
  end

  devise_for :admins
  devise_for :users

  mount Attachinary::Engine => "/attachinary"

  namespace :admins do
    resources :users
    resources :forms do
      resources :filled_forms
      resources :fields do
        collection do
          put :sort
        end
      end
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  store :data, accessors: [ :father_name, :phone_number, :mobile_number, :major, :minor, :birth_date, :identification_number, :student_identification_number ]

  attr_accessible :email, :password, :password_confirmation, :remember_me,
    :first_name, :last_name, :father_name, :phone_number, :mobile_number, :major, :minor, :birth_date, :identification_number, :student_identification_number

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :father_name, presence: true
  validates :phone_number, presence:true
  validates :mobile_number, presence: true
  validates :major, presence: true
  validates :birth_date, presence: true
  validates :identification_number, presence: true
  validates :student_identification_number, presence: true

  has_many :filled_forms, order: "updated_at DESC"


  def visible_forms
    Form.scoped
  end

  def fillable_forms
    Form.where(enabled: true)
  end

  def visible_filled_forms
    filled_forms
  end

  def editable_filled_forms
    filled_forms.where(state: [nil, 'not_reviewed'])
  end

  def name
    "#{first_name} #{last_name}"
  end
end

app/controllers/admins/users_controller.rb
class Admins::UsersController < ApplicationController
  before_filter :authenticate_admin!

  def index
    @users = User.all
    respond_with :admins, @users
  end

  def show
    @user = User.find(params[:id])
    respond_with :admins, @user
  end

  def new
    @user = User.new
    respond_with :admin, @user
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(params[:user])
    @user.save
    respond_with :admins, @user
  end

  def update
    @user = User.find(params[:id])
    @user.update_attributes(params[:user])
    respond_with :admins, @user
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    respond_with :admins, @user
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/users/edit.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%= t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human) %></h1>
</div>

<%= simple_form_for [:admins, @user], :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.error_notification %>
  <div class='form-inputs'>
    <%= f.input :email %>
    <%= f.input :first_name %>
    <%= f.input :last_name %>
    <%= f.input :father_name %>
    <%= f.input :phone_number %>
    <%= f.input :mobile_number %>
    <%= f.input :major %>
    <%= f.input :minor %>
    <%= f.input :birth_date %>
    <%= f.input :identification_number %>
    <%= f.input :student_identification_number %>
  </div>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
      admins_users_path, :class => 'btn' %>
  </div>
<% end %>
<h2><%= t '.update_password' %></h2>
<%= simple_form_for [:admins, @user], :html => { :class => 'form-horizontal' } do |f| %>
  <div class='form-inputs'>
    <%= f.input :password %>
  </div>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary', value: t('.update_password') %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
      admins_users_path, :class => 'btn' %>
  </div>
<% end %>

app/views/admins/users/index.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:major) %></th>
      <th><%= model_class.human_attribute_name(:identification_number) %></th>
      <th><%= model_class.human_attribute_name(:student_identification_number) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.name, admins_user_path(user) %></td>
        <td><%= user.email %></td>
        <td><%= user.major %></td>
        <td><%= user.identification_number %></td>
        <td><%= user.student_identification_number %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit_html")),
                      edit_admins_user_path(user), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy_html")),
                      admins_user_path(user),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new_html")),
            new_admins_user_path,
            :class => 'btn btn-primary' %>

app/views/admins/users/new.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human)%></h1>
</div>
<%= simple_form_for [:admins, @user], :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.error_notification %>
  <div class='form-inputs'>
    <%= f.input :email %>
    <%= f.input :password %>
    <%= f.input :first_name %>
    <%= f.input :last_name %>
    <%= f.input :father_name %>
    <%= f.input :phone_number %>
    <%= f.input :mobile_number %>
    <%= f.input :major %>
    <%= f.input :minor %>
    <%= f.input :birth_date %>
    <%= f.input :identification_number %>
    <%= f.input :student_identification_number %>
  </div>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                admins_users_path, :class => 'btn' %>
  </div>
<% end %>

app/views/admins/users/show.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<div>
  <p>
    <strong><%= model_class.human_attribute_name(:email) %>:</strong>
    <%= @user.email %>
  </p>
  <p>
    <strong><%= model_class.human_attribute_name(:first_name) %>:</strong>
    <%= @user.first_name %>
  </p>
  <p>
    <strong><%= model_class.human_attribute_name(:last_name) %>:</strong>
    <%= @user.last_name %>
  </p>
  <p>
    <strong><%= model_class.human_attribute_name(:student_identification_number) %>:</strong>
    <%= @user.student_identification_number %>
  </p>
  <p>
    <strong><%= model_class.human_attribute_name(:identification_number) %>:</strong>
    <%= @user.identification_number %>
  </p>
  <p>
    <strong><%= model_class.human_attribute_name(:major) %>:</strong>
    <%= @user.major %>
  </p>
  <p>
    <strong><%= model_class.human_attribute_name(:minor) %>:</strong>
    <%= @user.minor %>
  </p>
  <p>
    <strong><%= model_class.human_attribute_name(:phone_number) %>:</strong>
    <%= @user.phone_number %>
  </p>
  <p>
    <strong><%= model_class.human_attribute_name(:mobile_number) %>:</strong>
    <%= @user.mobile_number %>
  </p>
  <p>
    <strong><%= model_class.human_attribute_name(:birth_date) %>:</strong>
    <%= @user.birth_date %>
  </p>
  <p>
    <strong><%= model_class.human_attribute_name(:father_name) %>:</strong>
    <%= @user.father_name %>
  </p>
</div>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              admins_users_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit_html")),
              edit_admins_user_path(@user), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy_html")),
              admins_user_path(@user),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm")),
              :class => 'btn btn-danger' %>
</div>