config/routes.rb
Estedad::Application.routes.draw do

  root to: 'blogs#index'
  
  resources :pages
  resources :blogs
  resources :forms do
    resources :filled_forms, only: [:show, :create, :update, :new, :edit]
  end

  devise_for :admins
  devise_for :users

  mount Attachinary::Engine => "/attachinary"

  namespace :admins do
    resources :users
    resources :forms do
      resources :filled_forms
      resources :fields do
        collection do
          put :sort
        end
      end
    end
  end

end

app/controllers/admins/forms_controller.rb
class Admins::FormsController < ApplicationController
  before_filter :authenticate_admin!
  def index
    @forms = Form.all
    respond_with(:admins, @forms)
  end

  def show
    @form = Form.find(params[:id])
    respond_with(:admins, @form)
  end

  def new
    @form = Form.new
    respond_with(:admins, @form)
  end

  def edit
    @form = Form.find(params[:id])
  end

  def create
    @form = Form.new(params[:form])
    @form.save
    respond_with(:admins, @form)
  end

  def update
    @form = Form.find(params[:id])
    @form.update_attributes(params[:form])
    respond_with(:admins, @form)
  end

  def destroy
    @form = Form.find(params[:id])
    @form.destroy
    respond_with(:admins, @form)
  end
end

app/controllers/forms_controller.rb
class FormsController < ApplicationController
  before_filter :authenticate_user!
  def index
    @forms = current_user.visible_forms
    respond_with(@forms)
  end

  def show
    @form = current_user.visible_forms.find(params[:id])
    respond_with(@form)
  end
end

app/helpers/admins/forms_helper.rb
module Admins::FormsHelper
end

app/helpers/forms_helper.rb
module FormsHelper
  def not_enabled_alert
    content_tag :div, I18n.t('forms.not_enabled_html').html_safe, class: 'alert'
  end

  def link_to_admin_filled_fields(form)
    link_to t('.filled_form_count',
              count: form.filled_forms.count,
              not_reviewed_count: form.filled_forms.where(state: 'not_reviewed').count), admins_form_filled_forms_path(form)
  end
end

app/views/admins/forms/_fields.html.erb
<h2>فیلد‌ها</h2>
<%= t '.description' %>
<% if form.fields.count == 0 %>
  <div class="alert alert-block">
    <%= content_tag :p, t('.no_fields') %>
    <%= link_to t('.new_field_html'), new_admins_form_field_path(form), class: 'btn btn-primary' %>
  </div>
<% else %>
  <%= content_tag :ul, class: 'unstyled', id: 'fields',
    data: { update_url: sort_admins_form_fields_url(form) } do %>
    <%= content_tag_for :li, form.fields do |field| %>
      <span class='handle'><i class='icon-reorder'></i></span>
      <%= field.name %> (<%= translated_types field %>)
      <%= link_to t('helpers.links.edit_html'), edit_admins_form_field_path(form, field),
        class: 'btn btn-mini' %>
      <%= link_to t('helpers.links.destroy_html'), admins_form_field_path(form, field),
        method: :delete,
        confirm: t('.confirm', default: t('helpers.links.confirm')),
        class: 'btn btn-mini btn-danger' %>
    <% end %>
  <% end %>
  <%= link_to t('.new_field_html'), new_admins_form_field_path(form), class: 'btn btn-primary' %>
<% end %>

app/views/admins/forms/_form.html.erb
<%= simple_form_for [:admins, @form], :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.error_notification %>
  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :enabled %>
    <%= f.input :description %>
  </div>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
      admins_forms_path, :class => 'btn' %>
  </div>
<% end %>

app/views/admins/forms/edit.html.erb
<%- model_class = Form -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/admins/forms/index.html.erb
<%- model_class = Form -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:enabled) %></th>
      <th><%= model_class.human_attribute_name(:filled_forms) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @forms.each do |form| %>
      <tr>
        <td><%= link_to form.title, admins_form_path(form) %></td>
        <td><%= t form.enabled?.to_s %></td>
        <td><%= link_to_admin_filled_fields(form) %></td>
        <td><%= truncate form.description, length: 60, separator: ' ' %></td>
        <td>
          <%= link_to t('.edit_html', :default => t("helpers.links.edit_html")),
                      edit_admins_form_path(form), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy_html', :default => t("helpers.links.destroy_html")),
                      admins_form_path(form),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new_html', :default => t("helpers.links.new_html")),
            new_admins_form_path,
            :class => 'btn btn-primary' %>

app/views/admins/forms/new.html.erb
<%- model_class = Form -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/admins/forms/show.html.erb
<div class="page-header">
  <h1><%= @form.title %></h1>
</div>

<ul class="unstyled">
  <li><strong><%= Form.human_attribute_name(:enabled) %>:</strong>
  <%= t @form.enabled?.to_s %></li>
  <li><strong><%= Form.human_attribute_name(:description) %>:</strong>
  <%= content_tag :div, @form.description, data: { markdown: @form.description } %></li>
</ul>

<%= render 'fields', form: @form %>

<h2><%= Form.human_attribute_name(:filled_forms) %></h2>
<%= link_to_admin_filled_fields(@form) %>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
    admins_forms_path, :class => 'btn'  %>
  <%= link_to t('.edit_html', :default => t("helpers.links.edit_html")),
    edit_admins_form_path(@form), :class => 'btn' %>
  <%= link_to t('.destroy_html', :default => t("helpers.links.destroy_html")),
    admins_form_path(@form),
    method: 'delete',
    confirm: t('.confirm', default: t("helpers.links.confirm")),
    class: 'btn btn-danger' %>
</div>