config/routes.rb
Estedad::Application.routes.draw do

  root to: 'blogs#index'
  
  resources :pages
  resources :blogs
  resources :forms do
    resources :filled_forms, only: [:show, :create, :update, :new, :edit]
  end

  devise_for :admins
  devise_for :users

  mount Attachinary::Engine => "/attachinary"

  namespace :admins do
    resources :users
    resources :forms do
      resources :filled_forms
      resources :fields do
        collection do
          put :sort
        end
      end
    end
  end

end

app/views/layouts/_admin_navbar.html.erb
<div class="container nav-collapse">
  <ul class="nav">
    <li class='dropdown'>
      <%= link_to t('.filled_forms_html', count: FilledForm.where(state: [nil, :not_reviewed]).count), "#", class: 'dropdown-toggle', data: { toggle: 'dropdown'}  %>
      <ul class="dropdown-menu">
        <%= content_tag_for :li, Form.scoped do |form| %>
          <%= link_to filled_form_navbar_item(form), admins_form_filled_forms_path(form) %>
        <% end %>        
      </ul>
    </li>
    <li><%= link_to t('.blog'), blogs_path %></li>
    <li><%= link_to t('.forms'), admins_forms_path %></li>
    <li><%= link_to t('.users'), admins_users_path %></li>
    <li class='dropdown'>
      <%= link_to t('.pages_html'), '#', class: 'dropdown-toggle', data: { toggle: 'dropdown'}  %>
      <ul class='dropdown-menu'>
        <%= content_tag_for :li, Page.scoped do |page| %>
          <%= link_to page.title, page %>
        <% end %>
        <li class='divider'></li>
        <li><%= link_to t('.pages_index'), pages_path %></li>
      </ul>
    </li>
  </ul>
  <div class="pull-right">
    <ul class="nav pull-right">
      <li><%= link_to t('.logout_html'), destroy_admin_session_path, method: :delete %></li>
    </ul>
  </div>
</div><!--/.nav-collapse -->

app/views/layouts/_navbar.html.erb
<div class="container nav-collapse">
  <ul class="nav">
    <li><%= link_to t('.blog'), blogs_path  %></li>
    <li class='dropdown'>
      <%= link_to t('.pages_html'), '#' , class: 'dropdown-toggle', data: { toggle: 'dropdown'} %>
      <ul class='dropdown-menu'>
        <%= content_tag_for :li, Page.scoped do |page| %>
          <%= link_to page.title, page %>
        <% end %>
      </ul>
    </li>
  </ul>
  <div class="pull-right">
    <ul class="nav pull-right">
      <li><%= link_to t('.sign_up_html'), new_user_registration_path %></li>
      <li><%= link_to t('.sign_in_html'), new_user_session_path %></li>
    </ul>
  </div>
</div><!--/.nav-collapse -->

app/views/layouts/_user_navbar.html.erb
<div class="container nav-collapse">
  <ul class="nav">
    <li><%= link_to t('.blog'), blogs_path  %></li>
    <li><%= link_to t('.forms'), forms_path  %></li>
    <li class='dropdown'>
      <%= link_to t('.pages_html'), '#', class: 'dropdown-toggle', data: { toggle: 'dropdown'}  %>
      <ul class='dropdown-menu'>
        <%= content_tag_for :li, Page.scoped do |page| %>
          <%= link_to page.title, page %>
        <% end %>
      </ul>
    </li>
  </ul>
  <div class="pull-right">
    <ul class="nav pull-right">
      <li><%= link_to t('.prefrences_html'), edit_user_registration_path %></li>
      <li><%= link_to t('.logout_html'), destroy_user_session_path, method: :delete %></li>
    </ul>
  </div>
</div><!--/.nav-collapse -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="fa" dir='rtl'>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : t(:estedad_title) %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <!-- Javascripts
    ================================================== -->
    <%= javascript_include_tag "application" %>
    <%= cloudinary_js_config %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/"><%= t :estedad %></a>
          <% if admin_signed_in? %>
            <%= render 'layouts/admin_navbar' %>
          <% elsif user_signed_in? %>
            <%= render 'layouts/user_navbar' %>
          <% else%>
            <%= render 'layouts/navbar' %>
          <% end %>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <% flash.each do |level, content| %>
          <%= content_tag :div, class: "alert alert-#{flash_class level }"  do %>
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <%= content %>
          <% end %>
        <% end %>
        <%= yield %>
      </div>

      <footer>
      <hr />
      <p>V 1.4.0</p>
      <ul class='unstyled'>
        <% unless admin_signed_in? %>
          <li><%= link_to "<i class='icon-lock'></i> ورود مدیر".html_safe, new_admin_session_path %></li>
        <% end %>
      </ul>
      </footer>

    </div> <!-- /container -->


  </body>
</html>